### ISSUE TITLE
rLogin sample dapps not showing feedback after confirming actions with WalletConnect

### ISSUE THREAD

**Issue by miltonwg** [rsksmart/rLogin#50] opened 2021-01-08 21:52 UTC
With WalletConnect, when doing sign, sign typed data and send actions there is no text feedback show on the website.

This does not happen when using nifty or metamask.

**Comment by miltonwg** [comment] 2021-01-28 13:07
tested it with Defiant and rwallet.

**Comment by jessgusclark** [comment] 2021-02-11 11:19
I can't reproduce this. 

Tested with WalletConnect using rWallet and Mobile Metamaks. For sending and signing data, the responses appear below the buttons. Is it a specific wallet that you are using?

**Comment by jessgusclark** [comment] 2021-03-01 10:41
I tested this again with the [basic sample app](https://github.com/rsksmart/rlogin-sample-apps/tree/main/basic-dapp) which has a sign message feature and defiant wallet works correctly. I'm going to close this for now and if there are more specifics, please add them here and we can reopen and test.

### Request in Defiant wallet
![image](https://user-images.githubusercontent.com/766679/109486233-431dc780-7a8b-11eb-8bf5-694e2c99c947.png)


### Response on website
![image](https://user-images.githubusercontent.com/766679/109486159-2b464380-7a8b-11eb-903d-ecd736c39d48.png)

**Closed by jessgusclark** 2021-03-01 10:41 UTC
Labels: bug, wallet-connect
